import base64
import io
import soundfile as sf
import torch
from kokoro import KPipeline

# Initialize Kokoro pipeline once
_kokoro_pipeline = None

def _get_pipeline():
    global _kokoro_pipeline
    if _kokoro_pipeline is None:
        _kokoro_pipeline = KPipeline(lang_code='h')
    return _kokoro_pipeline

async def text_to_speech(text):
    pipeline = _get_pipeline()
    # Generate audio chunks
    generator = pipeline(text, voice='hf_alpha')

    # Concatenate chunks into a single waveform (24000 Hz)
    audio_segments = []
    for _, _, audio in generator:
        audio_segments.append(torch.tensor(audio))

    if not audio_segments:
        raise ValueError("No audio generated by Kokoro")

    waveform = torch.cat(audio_segments).numpy()
    # Write to in-memory WAV
    buf = io.BytesIO()
    sf.write(buf, waveform, 24000, format='WAV')
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode('utf-8')
    return f"data:audio/wav;base64,{b64}"
